// SPDX-FileCopyrightText: 2026 Harvest Station
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Goobstation.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Administration.PlayerObjectives;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class PlayerObjectivesWindow : DefaultWindow
{
    public event Action<string>? OnAddObjective;
    public event Action<string>? OnAddCustomObjective;
    public event Action<int>? OnRemoveObjective;
    public event Action<int, bool>? OnSetObjectiveComplete;

    public PlayerObjectivesWindow()
    {
        RobustXamlLoader.Load(this);

        ProtoIdEdit.OnTextChanged += args =>
        {
            AddButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
        };

        AddButton.OnPressed += _ =>
        {
            var proto = ProtoIdEdit.Text.Trim();
            if (!string.IsNullOrWhiteSpace(proto))
            {
                OnAddObjective?.Invoke(proto);
                ProtoIdEdit.Text = string.Empty;
                AddButton.Disabled = true;
            }
        };

        CustomTextEdit.OnTextChanged += args =>
        {
            AddCustomButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
        };

        AddCustomButton.OnPressed += _ =>
        {
            var text = CustomTextEdit.Text.Trim();
            if (!string.IsNullOrWhiteSpace(text))
            {
                OnAddCustomObjective?.Invoke(text);
                CustomTextEdit.Text = string.Empty;
                AddCustomButton.Disabled = true;
            }
        };
    }

    public void UpdateState(PlayerObjectivesEuiState state)
    {
        PlayerLabel.Text = Loc.GetString("admin-objectives-player-label", ("player", state.Username));

        ObjectivesList.RemoveAllChildren();

        if (state.Objectives.Length == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("admin-objectives-none"),
                FontColorOverride = Color.Gray
            };
            ObjectivesList.AddChild(empty);
            return;
        }

        foreach (var obj in state.Objectives.OrderBy(o => o.Index))
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var label = new Label
            {
                Text = $"({obj.ProgressPercent}%) {obj.Title}",
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 4, 0),
            };

            var capturedIndex = obj.Index;

            if (obj.IsCustom)
            {
                var toggleBtn = new Button
                {
                    Text = obj.IsComplete
                        ? Loc.GetString("admin-objectives-mark-incomplete-button")
                        : Loc.GetString("admin-objectives-mark-complete-button"),
                    MinWidth = 110,
                    Margin = new Thickness(0, 0, 4, 0)
                };
                var capturedComplete = obj.IsComplete;
                toggleBtn.OnPressed += _ => OnSetObjectiveComplete?.Invoke(capturedIndex, !capturedComplete);
                row.AddChild(label);
                row.AddChild(toggleBtn);
            }
            else
            {
                row.AddChild(label);
            }

            var removeBtn = new Button
            {
                Text = Loc.GetString("admin-objectives-remove-button"),
                MinWidth = 70,
            };
            removeBtn.OnPressed += _ => OnRemoveObjective?.Invoke(capturedIndex);

            row.AddChild(removeBtn);
            ObjectivesList.AddChild(row);
        }
    }
}
