// SPDX-FileCopyrightText: 2026 Harvest Station
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using Content.Shared.Administration;
using Content.Shared.Mobs.Components;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ControlMobWindow : DefaultWindow
{
    private PlayerInfo? _controller;
    private NetEntity? _targetEntity;
    private Button? _selectedTargetBtn;

    private readonly List<(NetEntity Net, string Name, Button Btn)> _entityEntries = new();

    public ControlMobWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void EnteredTree()
    {
        ControllerList.OnSelectionChanged += OnControllerSelected;
        TargetFilter.OnTextChanged += _ => FilterEntities();
        SubmitButton.OnPressed += OnSubmitPressed;
        PopulateEntityList();
    }

    private void PopulateEntityList()
    {
        TargetEntityList.RemoveAllChildren();
        _entityEntries.Clear();
        _targetEntity = null;
        _selectedTargetBtn = null;

        var entities = IoCManager.Resolve<IEntityManager>();
        var query = entities.AllEntityQueryEnumerator<MobStateComponent, MetaDataComponent>();
        var items = new List<(NetEntity, string)>();
        while (query.MoveNext(out var uid, out _, out var meta))
        {
            var net = entities.GetNetEntity(uid);
            var name = $"{meta.EntityName} [{net.Id}]";
            items.Add((net, name));
        }
        items.Sort((a, b) => string.Compare(a.Item2, b.Item2, StringComparison.OrdinalIgnoreCase));

        foreach (var (net, name) in items)
        {
            var btn = new Button { Text = name, HorizontalExpand = true };
            var capturedNet = net;
            btn.OnPressed += _ => SelectEntity(capturedNet, btn);
            TargetEntityList.AddChild(btn);
            _entityEntries.Add((net, name, btn));
        }
    }

    private void SelectEntity(NetEntity net, Button btn)
    {
        if (_selectedTargetBtn != null)
            _selectedTargetBtn.ModulateSelfOverride = null;
        _targetEntity = net;
        _selectedTargetBtn = btn;
        btn.ModulateSelfOverride = Color.LightGreen;
        UpdateButton();
    }

    private void FilterEntities()
    {
        var filter = TargetFilter.Text.Trim().ToLowerInvariant();
        foreach (var (_, name, btn) in _entityEntries)
        {
            btn.Visible = string.IsNullOrEmpty(filter) || name.ToLowerInvariant().Contains(filter);
        }
    }

    private void OnControllerSelected(PlayerInfo? info)
    {
        _controller = info;
        UpdateButton();
    }

    private void UpdateButton()
    {
        SubmitButton.Disabled = _controller == null || _targetEntity == null;
    }

    private void OnSubmitPressed(BaseButton.ButtonEventArgs _)
    {
        if (_controller == null || _targetEntity is not { } targetNet)
            return;

        IoCManager.Resolve<IClientConsoleHost>()
            .ExecuteCommand($"controlmobas \"{_controller.Username}\" {targetNet.Id}");
        Close();
    }
}
