// SPDX-FileCopyrightText: 2026 Harvest Station
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObjectivesLauncherWindow : DefaultWindow
{
    private PlayerInfo? _selectedPlayer;

    protected override void EnteredTree()
    {
        PlayerList.OnSelectionChanged += OnPlayerSelected;
        SubmitButton.OnPressed += OnSubmitPressed;
    }

    private void OnPlayerSelected(PlayerInfo? info)
    {
        _selectedPlayer = info;
        SubmitButton.Disabled = _selectedPlayer == null;
    }

    private void OnSubmitPressed(Robust.Client.UserInterface.Controls.BaseButton.ButtonEventArgs _)
    {
        if (_selectedPlayer == null)
            return;

        IoCManager.Resolve<IClientConsoleHost>()
            .ExecuteCommand($"playerobjectives \"{_selectedPlayer.Username}\"");
        Close();
    }
}
