// SPDX-FileCopyrightText: 2026 Harvest Station
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Mobs.Components;
using Content.Shared.Warps;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class TeleportToWindow : DefaultWindow
{
    private NetEntity? _selectedSource;
    private Button? _selectedSourceBtn;
    private NetEntity? _selectedDest;
    private Button? _selectedDestBtn;
    private string? _selectedWarp;
    private bool _warpMode;

    private readonly IClientConsoleHost _console;
    private readonly IEntityManager _entities;
    private readonly IPlayerManager _playerManager;

    private readonly List<(NetEntity Net, string Name, Button Btn)> _sourceEntries = [];
    private readonly List<(NetEntity Net, string Name, Button Btn)> _destEntries = [];

    public TeleportToWindow()
    {
        RobustXamlLoader.Load(this);
        _console = IoCManager.Resolve<IClientConsoleHost>();
        _entities = IoCManager.Resolve<IEntityManager>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();

        SourceFilter.OnTextChanged += _ => FilterList(_sourceEntries, SourceFilter.Text);
        DestEntityFilter.OnTextChanged += _ => FilterList(_destEntries, DestEntityFilter.Text);

        DestModePlayerButton.OnPressed += _ => SetWarpMode(false);
        DestModeWarpButton.OnPressed += _ => SetWarpMode(true);

        WarpFilter.OnTextChanged += _ => FilterWarpList();

        TeleportToTargetButton.OnPressed += _ => ExecuteTeleportToTarget();
        TeleportTargetToMeButton.OnPressed += _ => ExecuteTeleportTargetToMe();

        PopulateEntityLists();
        PopulateWarpList();
        UpdateButtons();
    }

    private void PopulateEntityLists()
    {
        var items = new List<(NetEntity, string)>();
        var query = _entities.AllEntityQueryEnumerator<MobStateComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out _, out var meta))
        {
            var net = _entities.GetNetEntity(uid);
            items.Add((net, $"{meta.EntityName} [{net.Id}]"));
        }
        items.Sort((a, b) => string.Compare(a.Item2, b.Item2, StringComparison.OrdinalIgnoreCase));

        PopulateEntityBox(SourceEntityList,
            _sourceEntries,
            items,
            (net, btn) =>
        {
            if (_selectedSourceBtn != null)
                _selectedSourceBtn.ModulateSelfOverride = null;

            _selectedSource = net;
            _selectedSourceBtn = btn;
            btn.ModulateSelfOverride = Color.LightGreen;
            UpdateButtons();
        });

        PopulateEntityBox(DestEntityList,
            _destEntries,
            items,
            (net, btn) =>
        {
            if (_selectedDestBtn != null)
                _selectedDestBtn.ModulateSelfOverride = null;

            _selectedDest = net;
            _selectedDestBtn = btn;
            _selectedWarp = null;
            btn.ModulateSelfOverride = Color.LightGreen;
            UpdateButtons();
        });
    }

    private static void PopulateEntityBox(BoxContainer container,
        List<(NetEntity Net, string Name, Button Btn)> entries,
        List<(NetEntity, string)> items,
        Action<NetEntity, Button> onSelect)
    {
        container.RemoveAllChildren();
        entries.Clear();
        foreach (var (net, name) in items)
        {
            var btn = new Button { Text = name, HorizontalExpand = true };
            var capturedNet = net;
            btn.OnPressed += _ => onSelect(capturedNet, btn);
            container.AddChild(btn);
            entries.Add((net, name, btn));
        }
    }

    private void FilterList(List<(NetEntity Net, string Name, Button Btn)> entries, string text)
    {
        var filter = text.Trim().ToLowerInvariant();
        foreach (var (_, name, btn) in entries)
        {
            btn.Visible = string.IsNullOrEmpty(filter) || name.ToLowerInvariant().Contains(filter);
        }
    }

    private void SetWarpMode(bool warp)
    {
        _warpMode = warp;
        DestEntityFilter.Visible = !warp;
        DestEntityScroll.Visible = !warp;
        WarpContainer.Visible = warp;
        DestModePlayerButton.Pressed = !warp;
        DestModeWarpButton.Pressed = warp;
        _selectedDest = null;
        if (_selectedDestBtn != null)
        {
            _selectedDestBtn.ModulateSelfOverride = null;
            _selectedDestBtn = null;
        }
        _selectedWarp = null;
        UpdateButtons();
    }

    private void PopulateWarpList()
    {
        WarpList.RemoveAllChildren();
        var names = new List<string>();
        var query = _entities.AllEntityQueryEnumerator<WarpPointComponent, MetaDataComponent>();
        while (query.MoveNext(out _, out var warp, out var meta))
        {
            names.Add(warp.Location ?? meta.EntityName);
        }

        names.Sort();
        foreach (var name in names)
        {
            AddWarpEntry(name);
        }
    }

    private void FilterWarpList()
    {
        var filter = WarpFilter.Text.Trim().ToLowerInvariant();
        foreach (var child in WarpList.Children)
        {
            if (child is Button btn)
                btn.Visible = string.IsNullOrEmpty(filter) || btn.Text!.ToLowerInvariant().Contains(filter);
        }
    }

    private void AddWarpEntry(string name)
    {
        var btn = new Button { Text = name, HorizontalExpand = true };
        btn.OnPressed += _ =>
        {
            _selectedWarp = name;
            _selectedDest = null;
            if (_selectedDestBtn != null)
            {
                _selectedDestBtn.ModulateSelfOverride = null;
                _selectedDestBtn = null;
            }

            foreach (var child in WarpList.Children)
            {
                if (child is Button b)
                    b.ModulateSelfOverride = b == btn ? Color.LightGreen : null;
            }
            UpdateButtons();
        };
        WarpList.AddChild(btn);
    }

    private void UpdateButtons()
    {
        var hasSource = _selectedSource != null;
        var hasDest = _warpMode ? _selectedWarp != null : _selectedDest != null;
        TeleportToTargetButton.Disabled = !hasSource || !hasDest;
        TeleportTargetToMeButton.Disabled = !hasSource;
    }

    private void ExecuteTeleportToTarget()
    {
        if (_selectedSource == null)
            return;

        if (_warpMode && _selectedWarp != null)
        {
            _console.ExecuteCommand($"tpto {_selectedSource.Value} \"{_selectedWarp}\"");
        }
        else if (_selectedDest != null)
        {
            _console.ExecuteCommand($"tpto {_selectedDest.Value} {_selectedSource.Value}");
        }
    }

    private void ExecuteTeleportTargetToMe()
    {
        if (_selectedSource == null)
            return;
        var mySession = _playerManager.LocalSession;
        if (mySession?.AttachedEntity is { } myEnt)
            _console.ExecuteCommand($"tpto {_entities.GetNetEntity(myEnt)} {_selectedSource.Value}");
    }
}
